##########
# This is the config file to set a base model, vae and some tools.
# Rename the file to `config.yml` before running the script.
# Execute `modal deploy ./app/setup.py` every time modify this file.
##########

##########
# You can use a diffusers model and VAE on hugging face.
version: "sd15" # 'sd15' or 'sdxl'.
model:
  name: stable-diffusion-1-5
  url: https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned.safetensors
vae:
  name: sd-vae-ft-mse
  url: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors
##########
# Add LoRA if you want to use one. You can use a download url such as the below.
# ex)
# loras:
#   - name: hogehoge.safetensors
#     url: https://hogehoge/xxxx
#   - name: fugafuga.safetensors
#     url: https://fugafuga/xxxx

##########
# You can use Textual Inversion and ControlNet also. Usage is the same as `loras`.
# ex)
# textual_inversions:
#   - name: hogehoge
#     url: https://hogehoge/xxxx
#   - name: fugafuga
#     url: https://fugafuga/xxxx
controlnets:
  - name: control_v11f1e_sd15_tile
    repo_id: lllyasviel/control_v11f1e_sd15_tile
